-- GUI 数据表
-- 存储GUI相关的所有数据和状态

TBoN.GUI = TBoN.GUI or {}
TBoN.GUI.Table = TBoN.GUI.Table or {}

-- 所有可用法术列表 (从gun_actions.lua提取)
TBoN.GUI.Table.all_spells = {
    "BOMB", "LIGHT_BULLET", "LIGHT_BULLET_TRIGGER", "LIGHT_BULLET_TIMER",
    "BULLET", "BULLET_TRIGGER", "BULLET_TIMER",
    "HEAVY_BULLET", "HEAVY_BULLET_TRIGGER", "HEAVY_BULLET_TIMER",
    "AIR_BULLET", "SLOW_BULLET", "SLOW_BULLET_TRIGGER", "SLOW_BULLET_TIMER",
    "HOOK", "BLACK_HOLE", "BLACK_HOLE_DEATH_TRIGGER",
    "WHITE_HOLE", "BLACK_HOLE_BIG", "WHITE_HOLE_BIG",
    "BLACK_HOLE_GIGA", "WHITE_HOLE_GIGA", "TENTACLE_PORTAL",
    "DECOY", "DECOY_TRIGGER", "SPITTER", "SPITTER_TIMER",
    "SPITTER_TIER_2", "SPITTER_TIER_2_TIMER", "SPITTER_TIER_3", "SPITTER_TIER_3_TIMER",
    "BUBBLESHOT", "BUBBLESHOT_TRIGGER", "DISC_BULLET", "DISC_BULLET_BIG", "DISC_BULLET_BIGGER",
    "BOUNCY_ORB", "BOUNCY_ORB_TIMER", "RUBBER_BALL",
    "ARROW", "POLLEN", "LANCE", "LANCE_HOLY",
    "ROCKET", "ROCKET_TIER_2", "ROCKET_TIER_3",
    "GRENADE", "GRENADE_TRIGGER", "GRENADE_TIER_2", "GRENADE_TIER_3",
    "MINE", "MINE_DEATH_TRIGGER", "PIPE_BOMB", "PIPE_BOMB_DEATH_TRIGGER",
    "EXPLOSIVE_PROJECTILE", "FIREBALL", "METEOR", "FLAMETHROWER",
    "ICEBALL", "SLIMEBALL", "DARKFLAME", "MISSILE",
    "FUNKY_SPELL", "PEBBLE", "DYNAMITE", "GLITTER_BOMB",
    "BUCKSHOT", "FREEZING_GAZE", "GLOWING_BOLT", "SPORE_POD",
    "GLUE_SHOT", "BOMB_DETONATOR", "LASER", "LASER_EMITTER",
    "DIGGER", "POWERDIGGER", "CHAINSAW", "LUMINOUS_DRILL",
    "TENTACLE", "HEAL_BULLET", "SPIRAL_SHOT", "MAGIC_SHIELD",
    "BIG_MAGIC_SHIELD", "CHAIN_BOLT", "FIREWORKS", "DEATH_CROSS",
    "INFESTATION", "WALL_HORIZONTAL", "WALL_VERTICAL", "WALL_SQUARE",
    "TEMPORARY_WALL", "TEMPORARY_PLATFORM", "PURPLE_EXPLOSION_FIELD",
    "DELAYED_SPELL", "LONG_DISTANCE_CAST", "TELEPORT_CAST",
    "SUPER_TELEPORT_CAST", "MIST_RADIOACTIVE", "MIST_ALCOHOL", "MIST_SLIME",
    "MIST_BLOOD", "CIRCLE_FIRE", "CIRCLE_ACID", "CIRCLE_OIL",
    "CIRCLE_WATER", "MATERIAL_WATER", "MATERIAL_OIL", "MATERIAL_BLOOD",
    "MATERIAL_ACID", "MATERIAL_CEMENT", "TELEPORT_PROJECTILE",
    "SWAPPER_PROJECTILE", "TELEPORT_PROJECTILE_SHORT", "TELEPORT_PROJECTILE_STATIC",
    "NUKE", "NUKE_GIGA", "FIREBALL_RAY", "LIGHTNING",
    "BALL_LIGHTNING", "LASER_LUMINOUS_DRILL", "LASER_EMITTER_FOUR",
    "LASER_EMITTER_CUTTER", "CHAIN_SHOT", "WALL_SPHERE",
    "SPELLS_TO_POWER", "ESSENCE_TO_POWER", "ZERO_DAMAGE",
    "HEAVY_SHOT", "LIGHT_SHOT", "KNOCKBACK", "RECOIL",
    "RECOIL_DAMPER", "SPEED", "EXPLOSIVE", "WATER_TO_POISON",
    "BLOOD_TO_ACID", "LAVA_TO_BLOOD", "LIQUID_TO_EXPLOSION",
    "TOXIC_TO_ACID", "STATIC_TO_SAND", "TRANSMUTATION", "RANDOM_SPELL",
    "RANDOM_PROJECTILE", "RANDOM_MODIFIER", "RANDOM_STATIC_PROJECTILE",
    "ALL_NUKES", "ALL_DISCS", "ALL_ROCKETS", "ALL_DEATHCROSSES",
    "ALL_BLACKHOLES", "ALL_ACID", "ALL_SPELLS", "SUMMON_PORTAL",
    "ADD_TRIGGER", "ADD_TIMER", "ADD_DEATH_TRIGGER", "LARPA_CHAOS",
    "LARPA_DOWNWARDS", "LARPA_UPWARDS", "LARPA_CHAOS_2", "LARPA_DEATH",
    "ALPHA", "GAMMA", "TAU", "OMEGA",
    "MU", "PHI", "SIGMA", "ZETA",
    "DIVIDE_2", "DIVIDE_3", "DIVIDE_4", "DIVIDE_10",
    "GRAVITY", "GRAVITY_ANTI", "PROJECTILE_HOMING_SHOOTER", "PROJECTILE_HOMING",
    "HOMING_ROTATE", "HOMING_SHOOTER", "AUTOGUIDE", "HOMING_ACCELERATING",
    "HOMING_CURSOR", "HOMING_AREA", "PIERCING_SHOT", "CLIPPING_SHOT",
    "DAMAGE", "DAMAGE_RANDOM", "BLOODLUST", "DAMAGE_FOREVER",
    "CRITICAL_HIT", "AREA_DAMAGE", "SPELLS_TO_NUKES", "DEATH_BLAST",
    "EXPLOSION", "EXPLOSION_LIGHT", "FIRE_BLAST", "POISON_BLAST",
    "ALCOHOL_BLAST", "THUNDER_BLAST", "BERSERK_FIELD", "POLYMORPH_FIELD",
    "CHAOS_POLYMORPH_FIELD", "ELECTROCUTION_FIELD", "FREEZE_FIELD",
    "REGENERATION_FIELD", "TELEPORTATION_FIELD", "LEVITATION_FIELD",
    "SHIELD_FIELD",
}

-- 法术显示名称映射（简化显示）
TBoN.GUI.Table.spell_display_names = {}
for i, spell in ipairs(TBoN.GUI.Table.all_spells) do
    TBoN.GUI.Table.spell_display_names[i] = spell:gsub("_", " ")
end

-- GUI状态变量
TBoN.GUI.Table.state = {
    initialized = false,
    
    -- 法术生成器状态
    spell = {
        selected_spell_index = 1,
        selected_spell_id = "BOMB",
        spawn_location = 1, -- 1: 背包, 2: 世界
        max_uses = 5,
        current_uses = 5,
        infinite_uses = true,
    },
    
    -- 法杖生成器状态
    wand = {
        -- 法杖基础属性
        name = "自定义法杖",
        shuffle = false,
        capacity = 5,
        cast_delay = 10,
        recharge_time = 30,
        mana_max = 500,
        mana_charge_speed = 150,
        spread_degrees = 3,
        always_cast = "",
        
        -- 法杖内法术列表
        spells = {},
        selected_spell_for_wand = 1,
        spell_max_uses = -1, -- -1 表示无限
        
        spawn_location = 1, -- 1: 背包, 2: 世界
    },
}
