TBoN.Callback.TBON_POST_PICKUP_MAGIC = "TBoN_POST_PICKUP_MAGIC"
TBoN.Callback.TBON_POST_PICKUP_WAND = "TBoN_POST_PICKUP_WAND"
TBoN.Callback.TBON_POST_WAND_SPAWN = "TBoN_POST_WAND_SPAWN"
TBoN.Callback.TBON_PRE_MAGIC_REMOVE = "TBoN_PRE_MAGIC_REMOVE"