gun = {
    {
        pos = Vector(25, 101),
        sprite = Sprite(),
        gun = false
    },
    {
        pos = Vector(25, 121),
        sprite = Sprite(),
        gun = false
    },
    {
        pos = Vector(25, 141),
        sprite = Sprite(),
        gun = false
    },
    {
        pos = Vector(25, 161),
        sprite = Sprite(),
        gun = false
    }
}
item = {
    {
        pos = Vector(25, 183),
        sprite = Sprite(),
        item = false
    },
    {
        pos = Vector(25, 203),
        sprite = Sprite(),
        item = false
    },
    {
        pos = Vector(25, 223),
        sprite = Sprite(),
        item = false
    },
    {
        pos = Vector(25, 243),
        sprite = Sprite(),
        item = false
    }
}
magic = {
    {
        pos = Vector(53, 43),
        sprite = Sprite(),
        magic = "BLACK_HOLE",
        type = true
    },
    {
        pos = Vector(53, 63),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(53, 83),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(53, 103),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(53, 123),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(53, 143),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(53, 163),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(53, 183),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(53, 203),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(53, 223),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(53, 243),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(73, 43),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(73, 63),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(73, 83),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(73, 103),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(73, 123),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(73, 143),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(73, 163),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {

        pos = Vector(73, 183),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(73, 203),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(73, 223),
        sprite = Sprite(),
        magic = false,
        type = false
    },
    {
        pos = Vector(73, 243),
        sprite = Sprite(),
        magic = false,
        type = false
    }
}
actions_map = {
    ["BOMB"] = 1,
    ["LIGHT_BULLET"] = 2,
    ["LIGHT_BULLET_TRIGGER"] = 3,
    ["LIGHT_BULLET_TRIGGER_2"] = 4,
    ["LIGHT_BULLET_TIMER"] = 5,
    ["BULLET"] = 6,
    ["BULLET_TRIGGER"] = 7,
    ["BULLET_TIMER"] = 8,
    ["HEAVY_BULLET"] = 9,
    ["HEAVY_BULLET_TRIGGER"] = 10,
    ["HEAVY_BULLET_TIMER"] = 11,
    ["AIR_BULLET"] = 12,
    ["SLOW_BULLET"] = 13,
    ["SLOW_BULLET_TRIGGER"] = 14,
    ["SLOW_BULLET_TIMER"] = 15,
    ["HOOK"] = 16,
    ["BLACK_HOLE"] = 17,
    ["BLACK_HOLE_DEATH_TRIGGER"] = 18,
    ["WHITE_HOLE"] = 19,
    ["BLACK_HOLE_BIG"] = 20,
    ["WHITE_HOLE_BIG"] = 21,
    ["BLACK_HOLE_GIGA"] = 22,
    ["WHITE_HOLE_GIGA"] = 23,
    ["TENTACLE_PORTAL"] = 24,
    ["SPITTER"] = 25,
    ["SPITTER_TIMER"] = 26,
    ["SPITTER_TIER_2"] = 27,
    ["SPITTER_TIER_2_TIMER"] = 28,
    ["SPITTER_TIER_3"] = 29,
    ["SPITTER_TIER_3_TIMER"] = 30,
    ["BUBBLESHOT"] = 31,
    ["BUBBLESHOT_TRIGGER"] = 32,
    ["DISC_BULLET"] = 33,
    ["DISC_BULLET_BIG"] = 34,
    ["DISC_BULLET_BIGGER"] = 35,
    ["BOUNCY_ORB"] = 36,
    ["BOUNCY_ORB_TIMER"] = 37,
    ["RUBBER_BALL"] = 38,
    ["ARROW"] = 39,
    ["POLLEN"] = 40,
    ["LANCE"] = 41,
    ["LANCE_HOLY"] = 42,
    ["ROCKET"] = 43,
    ["ROCKET_TIER_2"] = 44,
    ["ROCKET_TIER_3"] = 45,
    ["GRENADE"] = 46,
    ["GRENADE_TRIGGER"] = 47,
    ["GRENADE_TIER_2"] = 48,
    ["GRENADE_TIER_3"] = 49,
    ["GRENADE_ANTI"] = 50,
    ["GRENADE_LARGE"] = 51,
    ["MINE"] = 52,
    ["MINE_DEATH_TRIGGER"] = 53,
    ["PIPE_BOMB"] = 54,
    ["PIPE_BOMB_DEATH_TRIGGER"] = 55,
    ["FISH"] = 56,
    ["EXPLODING_DEER"] = 57,
    ["EXPLODING_DUCKS"] = 58,
    ["WORM_SHOT"] = 59,
    ["BOMB_DETONATOR"] = 60,
    ["LASER"] = 61,
    ["MEGALASER"] = 62,
    ["LIGHTNING"] = 63,
    ["BALL_LIGHTNING"] = 64,
    ["LASER_EMITTER"] = 65,
    ["LASER_EMITTER_FOUR"] = 66,
    ["LASER_EMITTER_CUTTER"] = 67,
    ["DIGGER"] = 68,
    ["POWERDIGGER"] = 69,
    ["CHAINSAW"] = 70,
    ["LUMINOUS_DRILL"] = 71,
    ["LASER_LUMINOUS_DRILL"] = 72,
    ["TENTACLE"] = 73,
    ["TENTACLE_TIMER"] = 74,
    ["HEAL_BULLET"] = 75,
    ["ANTIHEAL"] = 76,
    ["SPIRAL_SHOT"] = 77,
    ["MAGIC_SHIELD"] = 78,
    ["BIG_MAGIC_SHIELD"] = 79,
    ["CHAIN_BOLT"] = 80,
    ["FIREBALL"] = 81,
    ["METEOR"] = 82,
    ["FLAMETHROWER"] = 83,
    ["ICEBALL"] = 84,
    ["SLIMEBALL"] = 85,
    ["DARKFLAME"] = 86,
    ["MISSILE"] = 87,
    ["FUNKY_SPELL"] = 88,
    ["PEBBLE"] = 89,
    ["DYNAMITE"] = 90,
    ["GLITTER_BOMB"] = 91,
    ["BUCKSHOT"] = 92,
    ["FREEZING_GAZE"] = 93,
    ["GLOWING_BOLT"] = 94,
    ["SPORE_POD"] = 95,
    ["GLUE_SHOT"] = 96,
    ["BOMB_HOLY"] = 97,
    ["BOMB_HOLY_GIGA"] = 98,
    ["PROPANE_TANK"] = 99,
    ["BOMB_CART"] = 100,
    ["CURSED_ORB"] = 101,
    ["EXPANDING_ORB"] = 102,
    ["CRUMBLING_EARTH"] = 103,
    ["SUMMON_ROCK"] = 104,
    ["SUMMON_EGG"] = 105,
    ["SUMMON_HOLLOW_EGG"] = 106,
    ["TNTBOX"] = 107,
    ["TNTBOX_BIG"] = 108,
    ["SWARM_FLY"] = 109,
    ["SWARM_FIREBUG"] = 110,
    ["SWARM_WASP"] = 111,
    ["FRIEND_FLY"] = 112,
    ["ACIDSHOT"] = 113,
    ["THUNDERBALL"] = 114,
    ["FIREBOMB"] = 115,
    ["SOILBALL"] = 116,
    ["DEATH_CROSS"] = 117,
    ["DEATH_CROSS_BIG"] = 118,
    ["INFESTATION"] = 119,
    ["WALL_HORIZONTAL"] = 120,
    ["WALL_VERTICAL"] = 121,
    ["WALL_SQUARE"] = 122,
    ["TEMPORARY_WALL"] = 123,
    ["TEMPORARY_PLATFORM"] = 124,
    ["PURPLE_EXPLOSION_FIELD"] = 125,
    ["DELAYED_SPELL"] = 126,
    ["LONG_DISTANCE_CAST"] = 127,
    ["TELEPORT_CAST"] = 128,
    ["SUPER_TELEPORT_CAST"] = 129,
    ["CASTER_CAST"] = 130,
    ["MIST_RADIOACTIVE"] = 131,
    ["MIST_ALCOHOL"] = 132,
    ["MIST_SLIME"] = 133,
    ["MIST_BLOOD"] = 134,
    ["CIRCLE_FIRE"] = 135,
    ["CIRCLE_ACID"] = 136,
    ["CIRCLE_OIL"] = 137,
    ["CIRCLE_WATER"] = 138,
    ["MATERIAL_WATER"] = 139,
    ["MATERIAL_OIL"] = 140,
    ["MATERIAL_BLOOD"] = 141,
    ["MATERIAL_ACID"] = 142,
    ["MATERIAL_CEMENT"] = 143,
    ["TELEPORT_PROJECTILE"] = 144,
    ["TELEPORT_PROJECTILE_SHORT"] = 145,
    ["TELEPORT_PROJECTILE_STATIC"] = 146,
    ["SWAPPER_PROJECTILE"] = 147,
    ["TELEPORT_PROJECTILE_CLOSER"] = 148,
    ["NUKE"] = 149,
    ["NUKE_GIGA"] = 150,
    ["FIREWORK"] = 151,
    ["SUMMON_WANDGHOST"] = 152,
    ["TOUCH_GOLD"] = 153,
    ["TOUCH_WATER"] = 154,
    ["TOUCH_OIL"] = 155,
    ["TOUCH_ALCOHOL"] = 156,
    ["TOUCH_PISS"] = 157,
    ["TOUCH_GRASS"] = 158,
    ["TOUCH_BLOOD"] = 159,
    ["TOUCH_SMOKE"] = 160,
    ["DESTRUCTION"] = 161,
    ["MASS_POLYMORPH"] = 162,
    ["BURST_2"] = 163,
    ["BURST_3"] = 164,
    ["BURST_4"] = 165,
    ["BURST_8"] = 166,
    ["BURST_X"] = 167,
    ["SCATTER_2"] = 168,
    ["SCATTER_3"] = 169,
    ["SCATTER_4"] = 170,
    ["I_SHAPE"] = 171,
    ["Y_SHAPE"] = 172,
    ["T_SHAPE"] = 173,
    ["W_SHAPE"] = 174,
    ["CIRCLE_SHAPE"] = 175,
    ["PENTAGRAM_SHAPE"] = 176,
    ["I_SHOT"] = 177,
    ["Y_SHOT"] = 178,
    ["T_SHOT"] = 179,
    ["W_SHOT"] = 180,
    ["QUAD_SHOT"] = 181,
    ["PENTA_SHOT"] = 182,
    ["HEXA_SHOT"] = 183,
    ["SPREAD_REDUCE"] = 184,
    ["HEAVY_SPREAD"] = 185,
    ["RECHARGE"] = 186,
    ["LIFETIME"] = 187,
    ["LIFETIME_DOWN"] = 188,
    ["NOLLA"] = 189,
    ["SLOW_BUT_STEADY"] = 190,
    ["EXPLOSION_REMOVE"] = 191,
    ["EXPLOSION_TINY"] = 192,
    ["LASER_EMITTER_WIDER"] = 193,
    ["MANA_REDUCE"] = 194,
    ["BLOOD_MAGIC"] = 195,
    ["MONEY_MAGIC"] = 196,
    ["BLOOD_TO_POWER"] = 197,
    ["DUPLICATE"] = 198,
    ["QUANTUM_SPLIT"] = 199,
    ["GRAVITY"] = 200,
    ["GRAVITY_ANTI"] = 201,
    ["SINEWAVE"] = 202,
    ["CHAOTIC_ARC"] = 203,
    ["PINGPONG_PATH"] = 204,
    ["AVOIDING_ARC"] = 205,
    ["FLOATING_ARC"] = 206,
    ["FLY_DOWNWARDS"] = 207,
    ["FLY_UPWARDS"] = 208,
    ["HORIZONTAL_ARC"] = 209,
    ["LINE_ARC"] = 210,
    ["ORBIT_SHOT"] = 211,
    ["SPIRALING_SHOT"] = 212,
    ["PHASING_ARC"] = 213,
    ["TRUE_ORBIT"] = 214,
    ["BOUNCE"] = 215,
    ["REMOVE_BOUNCE"] = 216,
    ["HOMING"] = 217,
    ["ANTI_HOMING"] = 218,
    ["HOMING_WAND"] = 219,
    ["HOMING_SHORT"] = 220,
    ["HOMING_ROTATE"] = 221,
    ["HOMING_SHOOTER"] = 222,
    ["AUTOAIM"] = 223,
    ["HOMING_ACCELERATING"] = 224,
    ["HOMING_CURSOR"] = 225,
    ["HOMING_AREA"] = 226,
    ["PIERCING_SHOT"] = 227,
    ["CLIPPING_SHOT"] = 228,
    ["DAMAGE"] = 229,
    ["DAMAGE_RANDOM"] = 230,
    ["BLOODLUST"] = 231,
    ["DAMAGE_FOREVER"] = 232,
    ["CRITICAL_HIT"] = 233,
    ["AREA_DAMAGE"] = 234,
    ["SPELLS_TO_POWER"] = 235,
    ["ESSENCE_TO_POWER"] = 236,
    ["ZERO_DAMAGE"] = 237,
    ["HEAVY_SHOT"] = 238,
    ["LIGHT_SHOT"] = 239,
    ["KNOCKBACK"] = 240,
    ["RECOIL"] = 241,
    ["RECOIL_DAMPER"] = 242,
    ["SPEED"] = 243,
    ["ACCELERATING_SHOT"] = 244,
    ["DECELERATING_SHOT"] = 245,
    ["EXPLOSIVE_PROJECTILE"] = 246,
    ["CLUSTERMOD"] = 247,
    ["WATER_TO_POISON"] = 248,
    ["BLOOD_TO_ACID"] = 249,
    ["LAVA_TO_BLOOD"] = 250,
    ["LIQUID_TO_EXPLOSION"] = 251,
    ["TOXIC_TO_ACID"] = 252,
    ["STATIC_TO_SAND"] = 253,
    ["TRANSMUTATION"] = 254,
    ["RANDOM_EXPLOSION"] = 255,
    ["NECROMANCY"] = 256,
    ["LIGHT"] = 257,
    ["EXPLOSION"] = 258,
    ["EXPLOSION_LIGHT"] = 259,
    ["FIRE_BLAST"] = 260,
    ["POISON_BLAST"] = 261,
    ["ALCOHOL_BLAST"] = 262,
    ["THUNDER_BLAST"] = 263,
    ["BERSERK_FIELD"] = 264,
    ["POLYMORPH_FIELD"] = 265,
    ["CHAOS_POLYMORPH_FIELD"] = 266,
    ["ELECTROCUTION_FIELD"] = 267,
    ["FREEZE_FIELD"] = 268,
    ["REGENERATION_FIELD"] = 269,
    ["TELEPORTATION_FIELD"] = 270,
    ["LEVITATION_FIELD"] = 271,
    ["SHIELD_FIELD"] = 272,
    ["PROJECTILE_TRANSMUTATION_FIELD"] = 273,
    ["PROJECTILE_THUNDER_FIELD"] = 274,
    ["PROJECTILE_GRAVITY_FIELD"] = 275,
    ["VACUUM_POWDER"] = 276,
    ["VACUUM_LIQUID"] = 277,
    ["VACUUM_ENTITIES"] = 278,
    ["SEA_LAVA"] = 279,
    ["SEA_ALCOHOL"] = 280,
    ["SEA_OIL"] = 281,
    ["SEA_WATER"] = 282,
    ["SEA_SWAMP"] = 283,
    ["SEA_ACID"] = 284,
    ["SEA_ACID_GAS"] = 285,
    ["SEA_MIMIC"] = 286,
    ["CLOUD_WATER"] = 287,
    ["CLOUD_OIL"] = 288,
    ["CLOUD_BLOOD"] = 289,
    ["CLOUD_ACID"] = 290,
    ["CLOUD_THUNDER"] = 291,
    ["ELECTRIC_CHARGE"] = 292,
    ["MATTER_EATER"] = 293,
    ["FREEZE"] = 294,
    ["HITFX_BURNING_CRITICAL_HIT"] = 295,
    ["HITFX_CRITICAL_WATER"] = 296,
    ["HITFX_CRITICAL_OIL"] = 297,
    ["HITFX_CRITICAL_BLOOD"] = 298,
    ["HITFX_TOXIC_CHARM"] = 299,
    ["HITFX_EXPLOSION_SLIME"] = 300,
    ["HITFX_EXPLOSION_SLIME_GIGA"] = 301,
    ["HITFX_EXPLOSION_ALCOHOL"] = 302,
    ["HITFX_EXPLOSION_ALCOHOL_GIGA"] = 303,
    ["HITFX_PETRIFY"] = 304,
    ["ROCKET_DOWNWARDS"] = 305,
    ["ROCKET_OCTAGON"] = 306,
    ["FIZZLE"] = 307,
    ["BOUNCE_EXPLOSION"] = 308,
    ["BOUNCE_SPARK"] = 309,
    ["BOUNCE_LASER"] = 310,
    ["BOUNCE_LASER_EMITTER"] = 311,
    ["BOUNCE_LARPA"] = 312,
    ["BOUNCE_SMALL_EXPLOSION"] = 313,
    ["BOUNCE_LIGHTNING"] = 314,
    ["BOUNCE_HOLE"] = 315,
    ["FIREBALL_RAY"] = 316,
    ["LIGHTNING_RAY"] = 317,
    ["TENTACLE_RAY"] = 318,
    ["LASER_EMITTER_RAY"] = 319,
    ["FIREBALL_RAY_LINE"] = 320,
    ["FIREBALL_RAY_ENEMY"] = 321,
    ["LIGHTNING_RAY_ENEMY"] = 322,
    ["TENTACLE_RAY_ENEMY"] = 323,
    ["GRAVITY_FIELD_ENEMY"] = 324,
    ["CURSE"] = 325,
    ["CURSE_WITHER_PROJECTILE"] = 326,
    ["CURSE_WITHER_EXPLOSION"] = 327,
    ["CURSE_WITHER_MELEE"] = 328,
    ["CURSE_WITHER_ELECTRICITY"] = 329,
    ["ORBIT_DISCS"] = 330,
    ["ORBIT_FIREBALLS"] = 331,
    ["ORBIT_NUKES"] = 332,
    ["ORBIT_LASERS"] = 333,
    ["ORBIT_LARPA"] = 334,
    ["CHAIN_SHOT"] = 335,
    ["ARC_ELECTRIC"] = 336,
    ["ARC_FIRE"] = 337,
    ["ARC_GUNPOWDER"] = 338,
    ["ARC_POISON"] = 339,
    ["CRUMBLING_EARTH_PROJECTILE"] = 340,
    ["X_RAY"] = 341,
    ["UNSTABLE_GUNPOWDER"] = 342,
    ["ACID_TRAIL"] = 343,
    ["POISON_TRAIL"] = 344,
    ["OIL_TRAIL"] = 345,
    ["WATER_TRAIL"] = 346,
    ["GUNPOWDER_TRAIL"] = 347,
    ["FIRE_TRAIL"] = 348,
    ["BURN_TRAIL"] = 349,
    ["TORCH"] = 350,
    ["TORCH_ELECTRIC"] = 351,
    ["ENERGY_SHIELD"] = 352,
    ["ENERGY_SHIELD_SECTOR"] = 353,
    ["ENERGY_SHIELD_SHOT"] = 354,
    ["TINY_GHOST"] = 355,
    ["OCARINA_A"] = 356,
    ["OCARINA_B"] = 357,
    ["OCARINA_C"] = 358,
    ["OCARINA_D"] = 359,
    ["OCARINA_E"] = 360,
    ["OCARINA_F"] = 361,
    ["OCARINA_GSHARP"] = 362,
    ["OCARINA_A2"] = 363,
    ["KANTELE_A"] = 364,
    ["KANTELE_D"] = 365,
    ["KANTELE_DIS"] = 366,
    ["KANTELE_E"] = 367,
    ["KANTELE_G"] = 368,
    ["RANDOM_SPELL"] = 369,
    ["RANDOM_PROJECTILE"] = 370,
    ["RANDOM_MODIFIER"] = 371,
    ["RANDOM_STATIC_PROJECTILE"] = 372,
    ["DRAW_RANDOM"] = 373,
    ["DRAW_RANDOM_X3"] = 374,
    ["DRAW_3_RANDOM"] = 375,
    ["ALL_NUKES"] = 376,
    ["ALL_DISCS"] = 377,
    ["ALL_ROCKETS"] = 378,
    ["ALL_DEATHCROSSES"] = 379,
    ["ALL_BLACKHOLES"] = 380,
    ["ALL_ACID"] = 381,
    ["ALL_SPELLS"] = 382,
    ["SUMMON_PORTAL"] = 383,
    ["ADD_TRIGGER"] = 384,
    ["ADD_TIMER"] = 385,
    ["ADD_DEATH_TRIGGER"] = 386,
    ["LARPA_CHAOS"] = 387,
    ["LARPA_DOWNWARDS"] = 388,
    ["LARPA_UPWARDS"] = 389,
    ["LARPA_CHAOS_2"] = 390,
    ["LARPA_DEATH"] = 391,
    ["ALPHA"] = 392,
    ["GAMMA"] = 393,
    ["TAU"] = 394,
    ["OMEGA"] = 395,
    ["MU"] = 396,
    ["PHI"] = 397,
    ["SIGMA"] = 398,
    ["ZETA"] = 399,
    ["DIVIDE_2"] = 400,
    ["DIVIDE_3"] = 401,
    ["DIVIDE_4"] = 402,
    ["DIVIDE_10"] = 403,
    ["METEOR_RAIN"] = 404,
    ["WORM_RAIN"] = 405,
    ["RESET"] = 406,
    ["IF_ENEMY"] = 407,
    ["IF_PROJECTILE"] = 408,
    ["IF_HP"] = 409,
    ["IF_HALF"] = 410,
    ["IF_END"] = 411,
    ["IF_ELSE"] = 412,
    ["COLOUR_RED"] = 413,
    ["COLOUR_ORANGE"] = 414,
    ["COLOUR_GREEN"] = 415,
    ["COLOUR_YELLOW"] = 416,
    ["COLOUR_PURPLE"] = 417,
    ["COLOUR_BLUE"] = 418,
    ["COLOUR_RAINBOW"] = 419,
    ["COLOUR_INVIS"] = 420,
    ["RAINBOW_TRAIL"] = 421,
    ["CESSATION"] = 422,
}
