-- 这个表将保存4个法杖的详细状态
TBoN.Gun.Table.gun_states = {}

TBoN.Gun.Table.gun_info = {
    {
        name = false,
        shuffle = false,
        capacity = 0,
        cast_delay = 0,
        recharge_time = 0,
        mana_max = 0,
        mana_charge_speed = 0,
        spread_degrees = 0,
        always_cast = nil,  -- 始终施放的法术ID (nil表示无)
    },
    {
        name = false,
        shuffle = false,
        capacity = 0,
        cast_delay = 0,
        recharge_time = 0,
        mana_max = 0,
        mana_charge_speed = 0,
        spread_degrees = 0,
        always_cast = nil,
    },
    {
        name = false,
        shuffle = true,
        capacity = 0,
        cast_delay = 0,
        recharge_time = 0,
        mana_max = 0,
        mana_charge_speed = 0,
        spread_degrees = 0,
        always_cast = nil,
    },
    {
        name = false,
        shuffle = false,
        capacity = 0,
        cast_delay = 0,
        recharge_time = 0,
        mana_max = 0,
        mana_charge_speed = 0,
        spread_degrees = 0,
        always_cast = nil,
    }
}
-- Gun magic data with usage tracking
-- Each slot contains {magic_id, current_uses, max_uses} where:
-- magic_id: spell identifier (false for empty slots)
-- current_uses: -1 = infinite uses, 0 = empty slot, >0 = remaining uses
-- max_uses: maximum uses for this spell (-1 for infinite)
TBoN.Gun.Table.gun_magic_data = {
    { -- Gun 1
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}
    },
    { -- Gun 2
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}
    },
    { -- Gun 3
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}
    },
    { -- Gun 4
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}
    }
}
TBoN.Gun.Table.gun_info_dev = {
    {
        name = "wand_0000",
        shuffle = false,
        capacity = 10,
        cast_delay = 0,
        recharge_time = 0,
        mana_max = 990,
        mana_charge_speed = 90,
        spread_degrees = 0,
        always_cast = "BLACK_HOLE",  -- 始终施放的法术ID (nil表示无)
    },
    {
        name = false,
        shuffle = false,
        capacity = 0,
        cast_delay = 0,
        recharge_time = 0,
        mana_max = 0,
        mana_charge_speed = 0,
        spread_degrees = 0,
        always_cast = nil,
    },
    {
        name = false,
        shuffle = true,
        capacity = 0,
        cast_delay = 0,
        recharge_time = 0,
        mana_max = 0,
        mana_charge_speed = 0,
        spread_degrees = 0,
        always_cast = nil,
    },
    {
        name = false,
        shuffle = false,
        capacity = 0,
        cast_delay = 0,
        recharge_time = 0,
        mana_max = 0,
        mana_charge_speed = 0,
        spread_degrees = 0,
        always_cast = nil,
    }
}