-- 这个表将保存4个法杖的详细状态
TBoN.Gun.Table.gun_states = {}

TBoN.Gun.Table.gun_info = {
    {
        name = "wand_0000",
        shuffle = false,
        capacity = 9,
        cast_delay = 10,
        recharge_time = 10,
        mana_max = 5000,
        mana_charge_speed = 500,
        spread_degrees = 0,
    },
    {
        name = "wand_0567",
        shuffle = false,
        capacity = 20,
        cast_delay = 10,
        recharge_time = 10,
        mana_max = 1000,
        mana_charge_speed = 200,
        spread_degrees = 0,
    },
    {
        name = "wand_0001",
        shuffle = true,
        capacity = 17,
        cast_delay = 10,
        recharge_time = 10,
        mana_max = 800,
        mana_charge_speed = 150,
        spread_degrees = 0,
    },
    {
        name = false,
        shuffle = false,
        capacity = 0,
        cast_delay = 0,
        recharge_time = 0,
        mana_max = 0,
        mana_charge_speed = 0,
        spread_degrees = 0,
    }
}
-- Gun magic data with usage tracking
-- Each slot contains {magic_id, current_uses, max_uses} where:
-- magic_id: spell identifier (false for empty slots)
-- current_uses: -1 = infinite uses, 0 = empty slot, >0 = remaining uses
-- max_uses: maximum uses for this spell (-1 for infinite)
TBoN.Gun.Table.gun_magic_data = {
    { -- Gun 1
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = "LIGHT_BULLET_TRIGGER", current_uses = -1, max_uses = -1}, 
        {magic_id = "BLACK_HOLE", current_uses = -1, max_uses = -1}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}
    },
    { -- Gun 2
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = "TELEPORT_PROJECTILE", current_uses = -1, max_uses = -1}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}
    },
    { -- Gun 3
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = "HOMING_SHOOTER", current_uses = -1, max_uses = -1}, 
        {magic_id = "PROPANE_TANK", current_uses = -1, max_uses = -1}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}
    },
    { -- Gun 4
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}, 
        {magic_id = false, current_uses = 0, max_uses = 0}
    }
}